query($boundaries: ReadBoundaries, $order: ReadOrder ) {
  list(
    entity: "mutate",
    branch: ["request"],
    boundaries: $boundaries, 
    order: $order
  ) {
    id
    items {
      hashes {
        hash
      }
    }
  }
}
